name: Build & Deploy with Notification

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snakeapp:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/snakeapp:latest
          docker stop snakeapp || true && docker rm snakeapp || true
          docker run -d --name snakeapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/snakeapp:latest

      - name: Wait for App to Start
        run: sleep 10

      - name: Validate Application
        id: validate
        run: |
          if curl -s --fail http://localhost:5000; then
            echo "App is running" 
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "App validation failed"
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Deployment Status Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Deployment Status - ${{ needs.deploy.result}}'
          body: |
            Deployment has completed with status: ${{ needs.deploy.result || 'unknown' }}.
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
